version: '3.8'

services:
  backend:
    build:
      context: ./project-backend
    ports:
      - "8080:8080"
    depends_on:
      - database

  frontend:
    build:
      context: ./project-frontend
    ports:
      - "5173:80"

  database:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MFMS_DEV
      MYSQL_USER: gopi
      MYSQL_PASSWORD: gopi@1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
